### ISSUE TITLE
Invalid literal for int() with base 10

### ISSUE THREAD

**Issue by smutnyleszek** [natemccoy/udwg#2]
I tried using your script to get the wordlist from UD. Had some issues with installing Python 3+ on Mac, but finally made it and got this error:

```
Traceback (most recent call last):
  File "udwg.py", line 153, in <module>
    udwg(None, None)
  File "udwg.py", line 96, in udwg
    pageCount = getPageCount(soup)
  File "udwg.py", line 80, in getPageCount
    return int(pages.a.text)
ValueError: invalid literal for int() with base 10: 'az'
```

I can't Python at all, but I guess the `HTML` of UD could changed during last 2 years, right?

**Comment by natemccoy** [comment]
yeah probably, i need to update this script for the new site layout i'll look into it.

**Comment by natemccoy** [comment]
i just changed the code and also put a most popular words list in the repository for ease of download.
